name: actions

on:
  push:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v7
        with:
          name: ksj2tool-jar
          path: target/ksj2tool-*.jar
          archive: 'false'
          
      - name: GH Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3.0.1
        with:
          files: |
            target/ksj2tool-*.jar